# 配置文件环境
mode: dev

# 服务名称
serviceName: family-web

# 服务地址
address:
  domain: family-web.com
  ip: 192.168.10.14
  port: 8001

# 服务等级
serverLevel: v1

# 注册中心redis
redis:
  address: 192.168.10.14:6379
  password: biaoge666
  db: 0

# 数据库
mysql:
  address: 192.168.10.14:3306
  username: root
  password: biaoge666
  database: family-web

# 日志等级
logLevel: 0


# JWT
jwt:
  # 密钥
  secretKey: ledger
  # 有效期(单位:min)
  expireTime: 99999

static:
  # 静态文件目录
  dir: ./src/static/


