# 配置文件环境
mode: prod

# 服务名称
serviceName: family-web

# 服务地址
address:
  domain: family-web.com
  ip: 10.147.18.26
  port: 8001

# 服务等级
serverLevel: v1

# 注册中心redis
redis:
  address: 10.147.18.26:6379
  password: biaoge666
  db: 0

# 数据库
mysql:
  address: 10.147.18.26:3306
  username: root
  password: biaoge666
  database: family-web

# 日志等级
logLevel: 0


# JWT
jwt:
  # 密钥
  secretKey: ledger
  # 有效期(单位:小时)
  expireTime: 测试分类

static:
  # 静态文件目录
  dir: ./src/static/


